services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    restart: always
    volumes:
      - "/wp"
    networks:
      - nginxwordpress
    ports:
      - "433:433"
  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    restart: always
    volumes:
      - "/wp"
    networks:
      - nginxwordpress
      - wordpressmariadb
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - "/wp"
    networks:
      - wordpressmariadb

networks:
  nginxwordpress:
  wordpressmariadb:
