services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    restart: always
    volumes:
      - "~/Databases/WP_website_files:/var/www/html"
    networks:
      - nginxwordpress
    ports:
      - "433:433"
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    restart: always
    volumes:
      - "~/Databases/WP_website_files:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - nginxwordpress
      - wordpressmariadb

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - "~/Databases/WP_database:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - wordpressmariadb

networks:
  nginxwordpress:
  wordpressmariadb:
