#!/bin/sh
set -x

mysql_install_db

service mysql stop
mkdir -p /run/mysqld
chown -R mysql:mysql /run/mysqld

cat << END > /tmp/database_script.sql
CREATE DATABASE IF NOT EXISTS WP;
CREATE USER IF NOT EXISTS '$WP_USER_LOGIN'@'%' IDENTIFIED BY '$WP_USER_PASSWORD';
CREATE USER IF NOT EXISTS '$WP_BOSS_LOGIN'@'%' IDENTIFIED BY '$WP_BOSS_PASSWORD';
--GRANT ALL PRIVILEGES ON *.* TO '$WP_USER_LOGIN'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO '$WP_BOSS_LOGIN'@'%' WITH GRANT OPTION;
DELETE FROM mysql.user WHERE User='root';
FLUSH PRIVILEGES;
END

service mysql start && mysql < /tmp/database_script.sql
mysqladmin -u$WP_BOSS_LOGIN -p$WP_BOSS_PASSWORD shutdown
rm -f /tmp/database_script.sql
mysqld
